# Compiler config
compiler:
    useRubySass: true

# Modules config
modules:
    styles: true
    images: true
    scripts: true

# Project config
project:
    srcPath: src/
    destPath: dist/
